import USER_STORY_BUNDLE_CONFLICTING_METADATA_OPERATION_ALERT_MESSAGE from '@salesforce/label/c.USER_STORY_BUNDLE_CONFLICTING_METADATA_OPERATION_ALERT_MESSAGE';
import SEE_CONFLICTS from '@salesforce/label/c.SEE_CONFLICTS';
import USER_STORY_BUNDLE_CONFLICTING_COMPONENTS from '@salesforce/label/c.USER_STORY_BUNDLE_CONFLICTING_COMPONENTS';
import CANCEL from '@salesforce/label/c.Cancel';
import LOADING from '@salesforce/label/c.LOADING';

export const labels = {
    USER_STORY_BUNDLE_CONFLICTING_METADATA_OPERATION_ALERT_MESSAGE,
    SEE_CONFLICTS,
    USER_STORY_BUNDLE_CONFLICTING_COMPONENTS,
    CANCEL,
    LOADING
}