public class AutomationRuleConstants {
    public static final String AUTOMATION_CONNECTOR_CUSTOM = 'Custom';
    
    public static final String CONTINUOUS_DELIVERY = Label.Continuous_Delivery;

    public static final String EXECUTION_IMMEDIATE = 'Immediate';
    public static final String EXECUTION_SCHEDULED = 'Scheduled';

    public static final String SOURCE_ACTION_STATUS_SUCCESSFUL = 'Successful';
    public static final String SOURCE_ACTION_STATUS_ERROR = 'Error';
}