public class PromotionConstants {
    // STATUS VALUES

    public static final String STATUS_COMPLETED = 'Completed';
    public static final String STATUS_CANCELLED = 'Cancelled';
    public static final String STATUS_COMPLETED_SUCCESSFULLY = 'Completed Successfully';
    public static final String STATUS_COMPLETED_WITH_ERRORS = 'Completed with errors';
    public static final String STATUS_VALIDATED = 'Validated';
    public static final String STATUS_VALIDATION_FAILED = 'Validation failed';
    public static final String STATUS_DRAFT = 'Draft';
    public static final String STATUS_IN_PROGRESS = 'In Progress';
    public static final String STATUS_IN_PROGRESS_FOR_DEPLOYMENT = 'In progress';
    public static final String STATUS_MERGE_CONFLICT = 'Merge Conflict';
    public static final String STATUS_SUCCESSFUL = 'Successful';

    // GENERAL

    public static final String PROMOTED_USER_STORY = Label.Promoted_User_Story;
    public static final String BACK_PROMOTED_USER_STORY = Label.Back_Promoted_User_Story;
    public static final String AFTER_VALUE = 'after';
    public static final String BEFORE_VALUE = 'before';
    public static final String DO_NOT_RUN_JOB = 'doNotRunJob';
    public static final String STATUS_OUTDATED = 'Outdated';

    // FILE NAMES

    public static final String PROMOTE_FILE_NAME = 'Copado Promotion changes.json';
    public static final String DEPLOY_FILE_NAME = 'Copado Deploy changes.json';
    public static final String IGNORED_CHANGES_FILE_NAME = 'Ignored changes.json';

    // NOTIFICATION TEMPLATES

    public static final String PROMOTION_CONFLICT = 'Promotion_Conflict';
    public static final String PROMOTION_SUCCESS = 'Promotion_Success';
    public static final String PROMOTION_FAILED = 'Promotion_Failed';
    public static final String DEPLOY_SUCCESS = 'Deploy_Success';
    public static final String DEPLOY_FAILED = 'Deploy_Failed';

    // VOLUME OPTION

    public static final String VOLUME_OPTION_NAME = 'name';
    public static final String VOLUME_OPTION_VALUE = 'value';
    public static final String TRANSACTION_ID = 'transactionId';
}