import CONNECTION_BEHAVIOR_CONSIDERATION from '@salesforce/label/c.CONNECTION_BEHAVIOR_CONSIDERATION';
import AUTOMATED_DEPLOYMENT_TO_PRODUCTION from '@salesforce/label/c.AUTOMATED_DEPLOYMENT_TO_PRODUCTION';
import AUTOMATED_DEPLOYMENT_VALUE from '@salesforce/label/c.AUTOMATED_DEPLOYMENT_VALUE';
import USER_STORIES_PREREQUISITES from '@salesforce/label/c.USER_STORIES_PREREQUISITES';
import USER_STORIES_PREREQUISITES_VALUE from '@salesforce/label/c.USER_STORIES_PREREQUISITES_VALUE';
import BACK_PROMOTION_TO_NONADJACENT_ENV from '@salesforce/label/c.BACK_PROMOTION_TO_NONADJACENT_ENV';
import BACK_PROMOTION_TO_NONADJACENT_ENV_VALUE from '@salesforce/label/c.BACK_PROMOTION_TO_NONADJACENT_ENV_VALUE';
import GROUPING_LOGIC_FOR_BACK_PROMOTIONS from '@salesforce/label/c.GROUPING_LOGIC_FOR_BACK_PROMOTIONS';
import GROUPING_LOGIC_FOR_BACK_PROMOTIONS_VALUE from '@salesforce/label/c.GROUPING_LOGIC_FOR_BACK_PROMOTIONS_VALUE';
import CONNECTION_BEHAVIOR_CONSIDERATION_DETAILS from '@salesforce/label/c.CONNECTION_BEHAVIOR_CONSIDERATION_DETAILS';
import DOCUMENTATION from '@salesforce/label/c.DOCUMENTATION';
import CONNECTION_BEHAVIOR from '@salesforce/label/c.CONNECTION_BEHAVIOR';
import CONNECTION_BEHAVIOR_WARNING from '@salesforce/label/c.CONNECTION_BEHAVIOR_WARNING';
import HERE from '@salesforce/label/c.Here';
import CONNECTION_BEHAVIOR_OVERRIDING_WARNING from '@salesforce/label/c.CONNECTION_BEHAVIOR_OVERRIDING_WARNING';

export const label = {
    CONNECTION_BEHAVIOR_CONSIDERATION,
    AUTOMATED_DEPLOYMENT_TO_PRODUCTION,
    AUTOMATED_DEPLOYMENT_VALUE,
    USER_STORIES_PREREQUISITES,
    USER_STORIES_PREREQUISITES_VALUE,
    BACK_PROMOTION_TO_NONADJACENT_ENV,
    BACK_PROMOTION_TO_NONADJACENT_ENV_VALUE,
    GROUPING_LOGIC_FOR_BACK_PROMOTIONS,
    GROUPING_LOGIC_FOR_BACK_PROMOTIONS_VALUE,
    CONNECTION_BEHAVIOR_CONSIDERATION_DETAILS,
    DOCUMENTATION,
    CONNECTION_BEHAVIOR,
    CONNECTION_BEHAVIOR_WARNING,
    HERE,
    CONNECTION_BEHAVIOR_OVERRIDING_WARNING
};